### ISSUE TITLE
Translate English page to Korean.

### ISSUE THREAD

**Issue by dohvis** [pjwards/ward#51]
http://pjwards.com/login/
http://pjwards.com/accounts/register/

이 페이지들를 한글 / 영어버전으로 나누어 제공하는것이 어떨까요?

http://pjwards.com/login/?lang=ko
http://pjwards.com/login/?lang=en

**Comment by egaoneko** [comment]
의견 감사드립니다.
해당 부분에 대해서는 Django의 다국어 지원을 이용하는 방향으로 진행해보면 될 것 같아요. :)
